# Generated by Django 2.2 on 2020-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('dob', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
