# Generated by Django 2.2 on 2020-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_basic_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_basics',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
