# Generated by Django 2.2 on 2020-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_basic_details', '0002_user_basics_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_basics',
            name='days',
            field=models.IntegerField(blank=True),
        ),
    ]
