# Generated by Django 2.2 on 2020-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_basic_details', '0003_auto_20200704_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_basics',
            name='days',
        ),
        migrations.AddField(
            model_name='user_basics',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
