# Generated by Django 2.2 on 2020-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_basic_details', '0004_auto_20200704_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_basics',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
