# Generated by Django 2.2 on 2020-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('reply_body', models.CharField(blank=True, max_length=2000)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('reply_url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
