# Generated by Django 2.2 on 2020-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranger_query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_fake',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
