# Generated by Django 2.2 on 2020-07-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stranger_query', '0002_query_is_fake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='reply_body',
            new_name='reply',
        ),
    ]
