# Generated by Django 2.2 on 2020-07-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manager_news',
            new_name='news',
        ),
    ]
